name: Lint and Test

on:
  push:
    branches-ignore:
      - main
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - run: uv run ruff format --check
      - run: uv run ruff check

      - run: uv run -m unittest discover
